/*
 * This source file was generated by the Gradle 'init' task
 */
package org.interperter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Lox classUnderTest = new Lox();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
